"use client";

export { default as AdminAnalyticsPage } from "../../client/src/pages/admin/AdminAnalytics";
export { default as AdminArticleEditPage } from "../../client/src/pages/admin/AdminArticleEdit";
export { default as AdminArticlesPage } from "../../client/src/pages/admin/AdminArticles";
export { default as AdminCategoriesPage } from "../../client/src/pages/admin/AdminCategories";
export { default as AdminCollaboratorEditPage } from "../../client/src/pages/admin/AdminCollaboratorEdit";
export { default as AdminCollaboratorsPage } from "../../client/src/pages/admin/AdminCollaborators";
export { default as AdminExperientialGalleryPage } from "../../client/src/pages/admin/AdminProcessGallery";
export { default as AdminNewsEditPage } from "../../client/src/pages/admin/AdminNewsEdit";
export { default as AdminNewsPage } from "../../client/src/pages/admin/AdminNews";
export { default as AdminPage } from "../../client/src/pages/Admin";
export { default as AdminProjectEditPage } from "../../client/src/pages/AdminProjectEdit";
export { default as AdminProjectsPage } from "../../client/src/pages/admin/AdminProjects";
export { default as AdminRenderingGalleryPage } from "../../client/src/pages/admin/AdminRenderingGallery";
export { default as AdminScenicDirectoryEditPage } from "../../client/src/pages/admin/AdminScenicDirectoryEdit";
export { default as AdminScenicDirectoryPage } from "../../client/src/pages/admin/AdminScenicDirectory";
export { default as AdminTagsPage } from "../../client/src/pages/admin/AdminTags";
export { default as AdminTutorialEditPage } from "../../client/src/pages/admin/AdminTutorialEdit";
export { default as AdminTutorialsPage } from "../../client/src/pages/admin/AdminTutorials";
