type: project
discipline: rendering
slug: bell-book-and-candle
title: Bell, Book, and Candle
status: published
featured: false
excerpt: >-
  Bell, Book and Candle was designed as a grounded, realistic interior that supports the play’s wit and intimacy while
  quietly framing its supernatural undercurrents. The scenic design focused on creating a believable, mid-century
  apartment environment with a warm domestic scale and a distinctive green palette that subtly heightened the play’s
  mood without pushing the space into abstraction.
seoTitle: Bell, Book, and Candle
seoDescription: >-
  Bell, Book and Candle was designed as a grounded, realistic interior that supports the play’s wit and intimacy while
  quietly framing its supernatural undercurrents. The scenic design focused on creating a believable, mid-century
  apartment environment with a warm domestic scale and a distinctive green palette that subtly heightened the play’s
  mood without pushing the space into abstraction.
seoKeywords: []
client: Okoboji Summer Theatre
location: Okoboji, IA
year: 2025
month: 7
cover:
  asset: project-images/project-90016-gallery-150203.webp
  alt: Bell, Book, and Candle rendering project cover image
publishedAt: '2026-02-19T11:01:52.275Z'
updatedAt: '2026-02-19T11:01:52.275Z'
