type: project
discipline: rendering
slug: urinetown
title: Urinetown
status: published
featured: false
excerpt: >-
  Explore the innovative scenic design of Urinetown, a satirical musical that cleverly tackles a dystopian water
  shortage. Discover how visuals enhance storytelling!
seoTitle: Urinetown
seoDescription: >-
  Explore the innovative scenic design of Urinetown, a satirical musical that cleverly tackles a dystopian water
  shortage. Discover how visuals enhance storytelling!
seoKeywords: []
client: University of Missouri
location: Columbia, MO
year: 2024
month: 11
cover:
  asset: project-images/project-90041-gallery-150082.webp
  alt: Urinetown rendering project cover image
publishedAt: '2026-02-19T11:01:55.422Z'
updatedAt: '2026-02-19T11:01:55.422Z'
