siteName: Brandon PT Davis
siteUrl: https://www.brandonptdavis.com
title: Brandon PT Davis | Scenic Designer
description: >-
  Union scenic designer in Southern California creating story-driven environments for regional theatre, summer stock,
  and academic production.
email: info@brandonptdavis.com
social:
  instagram: https://www.instagram.com/brandonptdavisdesign
  linkedin: https://www.linkedin.com/in/brandonptdavis
  youtube: https://www.youtube.com/@brandonptdavis
  pinterest: https://www.pinterest.com/BrandonPTDavis/
