export type BecomingPhoto = {
  id: string;
  title: string;
  location: string;
  caption: string;
  alt: string;
  src: string;
  width: number;
  height: number;
  takenAt: string;
};

export const becomingPhotos = [
  { id: "becoming-01", title: "Tower in fog", location: "City street", caption: "The building keeps climbing after the eye loses it, a vertical thought swallowed by weather.", alt: "A tall glass tower disappearing into fog beside another high-rise.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-01-3488cb96a7.jpeg", width: 915, height: 1280, takenAt: "2014-12-23T11:05:54" },
  { id: "becoming-02", title: "Street murals", location: "Urban street", caption: "Sun, paint, and parked metal make the block feel improvised, as if the walls are still deciding what they want to be.", alt: "A street with colorful murals on garage doors and a parked van.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-02-023d0687f5.jpeg", width: 1280, height: 915, takenAt: "2015-03-19T13:16:38" },
  { id: "becoming-04", title: "Blue hour towers", location: "Downtown", caption: "At dusk the city turns theatrical, all silhouette and colored light before the night fully commits.", alt: "Downtown towers and a church spire at blue hour with colored lights in the skyline.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-04-7e13030ee4.jpeg", width: 854, height: 1280, takenAt: "2015-12-12T17:06:22" },
  { id: "becoming-06", title: "Storefront frame", location: "Columbia, Missouri", caption: "The sign does the loud work, but the real picture is the glowing rectangle of labor behind it.", alt: "The Shakespeare's Pizza storefront at night with lit signs and kitchen windows.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-06-23652d7da9.jpeg", width: 960, height: 1280, takenAt: "2017-01-24T19:09:13" },
  { id: "becoming-07", title: "Water Tower Place", location: "Chicago, Illinois", caption: "Stone, glass, grid, and height crowd together until the city reads like a stack of competing histories.", alt: "Chicago buildings around Water Tower Place with historic stone architecture and tall modern towers.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-07-e228269595.jpeg", width: 1280, height: 1280, takenAt: "2017-01-26T08:41:16" },
  { id: "becoming-09", title: "Aqua building", location: "Irvine, California", caption: "A building softened by color and rounded glass, more object than facade in the afternoon sun.", alt: "An aqua and glass building with rounded forms, hedges, and a partly cloudy sky.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-09-b3156ff352.jpeg", width: 1024, height: 1280, takenAt: "2017-09-03T16:49:49" },
  { id: "becoming-10", title: "White circle", location: "Coastal park", caption: "The figures gather under the tree with strange ceremony, bright and still against the fading coast.", alt: "White rabbit sculptures arranged in a circle on grass near a coastal park.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-10-8b749e9169.jpeg", width: 1280, height: 960, takenAt: "2017-09-16T18:14:51" },
  { id: "becoming-11", title: "Wires", location: "Street edge", caption: "Every line finds another line, and the sky becomes a score for small waiting shapes.", alt: "A utility pole and many overhead wires silhouetted against a gray sky.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-11-9d6f21b2ca.jpeg", width: 960, height: 1280, takenAt: "2018-08-26T08:02:03" },
  { id: "becoming-12", title: "Lobby color", location: "Public interior", caption: "A waiting room pretending to be landscape, with red walls, yellow lockers, and strangers resting inside the composition.", alt: "A colorful public lobby with red walls, yellow lockers, a scenic wall image, and people seated.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-12-7e9e5ff87b.jpeg", width: 1280, height: 915, takenAt: "2018-12-18T13:29:49" },
  { id: "becoming-13", title: "Pinned walls", location: "Process space", caption: "Before finish, before paint, before illusion: just openings, shadows, and the blunt honesty of construction.", alt: "A black-and-white view of unfinished scenic wall units with window openings and textured plywood.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-13-1f3cd0bf26.jpeg", width: 721, height: 1280, takenAt: "2019-11-04T14:36:05" },
  { id: "becoming-14", title: "Deck shadows", location: "Ship deck", caption: "The deck is almost overdrawn by light, each railing and support leaving another piece of geometry behind.", alt: "A person walking on a bright ship deck beneath curved white davits and long shadows.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-14-7d00e30d63.jpeg", width: 915, height: 1280, takenAt: "2019-12-16T08:35:34" },
  { id: "becoming-16", title: "Brick facade", location: "Chicago, Illinois", caption: "A wall of windows and ornament, held flat by parked cars and late color at the curb.", alt: "A detailed brick apartment facade with parked cars in front.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-16-8007c16fd0.jpeg", width: 1280, height: 1280, takenAt: "2021-04-25T13:49:05" },
  { id: "becoming-17", title: "Cloud Gate", location: "Chicago, Illinois", caption: "The plaza folds into itself, a public mirror making the city briefly liquid.", alt: "Cloud Gate in Chicago reflecting the surrounding plaza and skyline.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-17-fc50c33cbb.jpeg", width: 1280, height: 960, takenAt: "2021-05-09T12:51:36" },
  { id: "becoming-18", title: "Wolfy's sign", location: "Chicago, Illinois", caption: "A sign with no interest in subtlety, turning lunch into scale, color, and pure roadside performance.", alt: "The Wolfy's Vienna Beef sign with a large red hot dog shape above the street.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-18-2eb836edfb.jpeg", width: 720, height: 1280, takenAt: "2021-05-30T18:04:40" },
  { id: "becoming-19", title: "University of Missouri", location: "Columbia, Missouri", caption: "Stone, tracery, and a clock face carrying the weight of campus memory upward into the sky.", alt: "A University of Missouri stone clock tower photographed from below against a blue sky.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-19-4c0505a3f0.jpeg", width: 769, height: 1280, takenAt: "2021-11-13T16:06:48" },
  { id: "becoming-20", title: "Alley aperture", location: "City alley", caption: "A strip of blue above fire escapes and dark walls, narrow enough to feel discovered rather than seen.", alt: "A city alley looking upward between tall buildings toward a bright blue sky.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-20-3553744112.jpeg", width: 768, height: 1280, takenAt: "2021-12-21T13:51:12" },
  { id: "becoming-21", title: "Dry field", location: "Meadow", caption: "The whole field gathers around a few brittle stems, making a tiny foreground feel like weather.", alt: "A close view of dried field plants with a meadow and blue sky in the background.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-21-5688778081.jpeg", width: 720, height: 1280, takenAt: "2022-10-08T14:52:13" },
  { id: "becoming-22", title: "Autumn portrait", location: "Outdoors", caption: "A face in warm leaves and broken sun, the background dissolving just enough to hold the moment still.", alt: "A close portrait of a smiling woman in front of softly blurred autumn leaves.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-22-5e6bf5cf43.jpeg", width: 960, height: 1280, takenAt: "2022-10-08T14:53:13" },
  { id: "becoming-23", title: "Vertical texture", location: "Forest", caption: "Trunks rise like a quiet interior, all columns, grain, and filtered green overhead.", alt: "Tall trees rising vertically in a dense green forest.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-23-544e4d2267.jpeg", width: 720, height: 1280, takenAt: "2022-11-22T12:56:42" },
  { id: "becoming-24", title: "Painted village", location: "Leavenworth, Washington", caption: "A facade fully committed to its fiction, with color and trim doing the work of place-making.", alt: "A Bavarian-style building with flags, painted trim, and snow along the street.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-24-b29db9171b.jpeg", width: 1025, height: 1280, takenAt: "2022-12-27T11:58:22" },
  { id: "becoming-25", title: "High shelf", location: "Home", caption: "A shelf becomes a lookout, and the room below turns into scenery from the wrong angle.", alt: "An orange cat sitting on a high wooden shelf above white kitchen containers.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-25-daecbd906e.jpeg", width: 769, height: 1280, takenAt: "2023-06-06T01:29:35" },
  { id: "becoming-26", title: "Threshold", location: "Walkway", caption: "The tunnel narrows everything toward a clean circle of sky, a small rehearsal for arrival.", alt: "A white ribbed pedestrian tunnel with a concrete path rising toward a circular opening.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-26-ab44807bc3.jpeg", width: 1025, height: 1280, takenAt: "2023-06-26T13:48:16" },
  { id: "becoming-27", title: "Wall character", location: "Street wall", caption: "A person, a painted creature, and a flat wall briefly agree on scale.", alt: "A person standing beneath a large panda mural painted on a light wall.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-27-36e4da5610.jpeg", width: 720, height: 1280, takenAt: "2023-08-18T16:11:15" },
  { id: "becoming-28", title: "Shop volume", location: "Scene shop", caption: "The shop holds its breath before the work becomes visible: lumber, lifts, ladders, and overhead steel.", alt: "A scene shop interior with ladders, platforms, lumber, and people working at a table.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-28-a9ea8487c3.jpeg", width: 720, height: 1280, takenAt: "2023-10-12T14:54:32" },
  { id: "becoming-31", title: "Fence watch", location: "Fence line", caption: "The fence cuts the frame in two, leaving one small witness above the gray wash of sky.", alt: "A gray cat perched on top of a dark wooden fence against a pale sky.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-31-47375b07d9.jpeg", width: 960, height: 1280, takenAt: "2016-12-10T14:43:02" },
  { id: "becoming-32", title: "Oceano sign", location: "Roadside", caption: "A weathered sign leans out from the wall like a small coastal promise at the edge of the road.", alt: "An Oceano Market and Gas sign mounted above a sidewalk and roadside wall.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-32-660b326b9b.jpeg", width: 768, height: 1280, takenAt: "2017-06-22T17:23:33" },
  { id: "becoming-33", title: "Blue skylight", location: "Interior structure", caption: "Ironwork and glass pull the eye upward until the ceiling starts to feel like open air.", alt: "An interior view looking up through a blue glass skylight with ornate ironwork.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-33-7bab8096c6.jpeg", width: 1025, height: 1280, takenAt: "2020-07-01T14:45:52" },
  { id: "becoming-34", title: "Yellow railcar", location: "Rail display", caption: "Primary color, summer light, and a found bit of play turn the old railcar into a bright little stage.", alt: "A person standing on the ladder of a yellow railcar in bright sunlight.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-34-522d2eaed9.jpeg", width: 960, height: 1280, takenAt: "2020-07-02T12:35:17" },
  { id: "becoming-35", title: "Metra entrance", location: "Transit entrance", caption: "The entrance blooms out of the sidewalk, delicate metalwork holding a red glow against the evening.", alt: "A Metra entrance with ornate metalwork, red lamps, and a blue evening sky.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-35-d1b0277570.jpeg", width: 960, height: 1280, takenAt: "2020-11-08T16:05:21" },
  { id: "becoming-36", title: "Platform frame", location: "Transit platform", caption: "Tracks, steel, and old windows layer into a city seen from between movements.", alt: "An elevated train platform with tracks, steel framing, and brick buildings beyond.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-36-e868d6c3f9.jpeg", width: 1024, height: 1280, takenAt: "2021-03-12T16:33:56" },
  { id: "becoming-37", title: "Mayne marquee", location: "Night street", caption: "The marquee throws color into the dark, making the sidewalk feel briefly ceremonial.", alt: "The Mayne theatre marquee glowing at night with blue and red neon.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-37-aa4665cc5c.jpeg", width: 1024, height: 1280, takenAt: "2021-03-19T20:46:36" },
  { id: "becoming-38", title: "Capitol steps", location: "Civic architecture", caption: "All columns and weather, the building holds its pose under a sky heavy enough to press back.", alt: "A domed civic building with columns and broad steps under gray clouds.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-38-b01ff47e43.jpeg", width: 1280, height: 914, takenAt: "2021-09-04T16:42:53" },
  { id: "becoming-39", title: "Glenn's sign", location: "Night street", caption: "The neon hangs in the dark like handwriting, soft at the edges and bright where it matters.", alt: "A glowing Glenn's Cafe sign at night above a city sidewalk.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-39-b436d96054.jpeg", width: 768, height: 1280, takenAt: "2021-09-15T20:47:56" },
  { id: "becoming-40", title: "Green car", location: "Street parking", caption: "A little green form at the curb, rounded and stubborn, carrying its own weathered charm.", alt: "A green vintage Volkswagen Beetle parked on a city street.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-40-83f8303918.jpeg", width: 1280, height: 1024, takenAt: "2023-12-24T12:53:12" },
  { id: "becoming-41", title: "Rocket court", location: "Shopping plaza", caption: "Space travel rendered at plaza scale, heroic and oddly domestic among storefronts and passersby.", alt: "A model space shuttle and orange rocket boosters displayed in an open shopping plaza.", src: "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/becoming/becoming-41-bc5acd79d4.jpeg", width: 768, height: 1280, takenAt: "2026-01-18T15:56:10" },
] satisfies BecomingPhoto[];
