// Auto-generated by scripts/generate-local-portfolios.mjs
// Do not edit manually. Re-run the generator after portfolio DB changes.

export const generatedRenderingProjects = [
  {
    "id": 2,
    "title": "The Northwind Mare Tavern",
    "slug": "the-northwind-mare-tavern",
    "excerpt": "A fantasy tavern emerges from twilight mist—carved horse-head gables, glowing lanterns, stone walls weathered by imagined centuries. Emberreach invites guests into a Tamriel-inspired realm where dining becomes adventure, and every detail whispers of distant quests and fireside tales.",
    "designNotes": "Image set for The Northwind Mare Tavern — (2026). The work balances emotional atmosphere with stage logic, helping teams evaluate ideas before they are built. A fantasy tavern emerges from twilight mist—carved horse-head gables, glowing lanterns, stone walls weathered by imagined centuries.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/portfolio-images/projects/120001/image-150061.webp",
    "client": "",
    "location": "",
    "year": 2026,
    "month": 1,
    "status": "draft",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "The Northwind Mare Tavern - Fantasy Scenic Design Rendering",
    "seoDescription": "Explore Brandon PT Davis's scenic rendering of The Northwind Mare Tavern, a fantasy-inspired experiential design. Immerse yourself in a Tamriel-esque world of adventure and detailed craftsmanship.",
    "seoKeywords": "fantasy tavern,scenic design,experiential design,rendering,Tamriel,Brandon PT Davis,set design,themed environment,concept art,entertainment design",
    "createdAt": "2026-02-19T08:57:56.048Z",
    "updatedAt": "2026-02-19T08:57:56.048Z",
    "publishedAt": "2026-02-19T08:57:56.048Z",
    "images": []
  },
  {
    "id": 9,
    "title": "The Glass Menagerie",
    "slug": "the-glass-menagerie",
    "excerpt": "The Glass Menagerie at Maples Repertory Theatre, directed by Kimberly Braun, was staged as a memory play shaped by Tom Wingfield’s recollection rather than a literal apartment. The scenic environment emphasized fluid movement and emotional geography, supporting the play’s themes of longing, confinement, and escape.\n",
    "designNotes": "Visualization sequence for The Glass Menagerie — Maples Repertory Theatre (2025). Renderings are used here as decision tools, aligning scenic intent with directorial storytelling goals. The Glass Menagerie at Maples Repertory Theatre, directed by Kimberly Braun, was staged as a memory play shaped by Tom Wingfield’s recollection rather than a literal apartment.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90010-gallery-150168.webp",
    "client": "Maples Repertory Theatre",
    "location": " Macon, MO",
    "year": 2025,
    "month": 10,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "The Glass Menagerie",
    "seoDescription": "The Glass Menagerie at Maples Repertory Theatre, directed by Kimberly Braun, was staged as a memory play shaped by Tom Wingfield’s recollection rather than a literal apartment. The scenic environment emphasized fluid movement and emotional geography, supporting the play’s themes of longing, confinement, and escape.\n",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:01:51.231Z",
    "updatedAt": "2026-02-19T11:01:51.231Z",
    "publishedAt": "2026-02-19T11:01:51.231Z",
    "images": [
      {
        "id": 14,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90010-gallery-150168.webp",
        "altText": "Scenic rendering for The Glass Menagerie at Maples Repertory Theatre. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 10,
    "title": "Bell, Book, and Candle",
    "slug": "bell-book-and-candle",
    "excerpt": "Bell, Book and Candle was designed as a grounded, realistic interior that supports the play’s wit and intimacy while quietly framing its supernatural undercurrents. The scenic design focused on creating a believable, mid-century apartment environment with a warm domestic scale and a distinctive green palette that subtly heightened the play’s mood without pushing the space into abstraction.",
    "designNotes": "Scenic rendering series for Bell, Book, and Candle — Okoboji Summer Theatre (2025). This rendering package supports early collaboration by translating concept language into actionable visual cues. Bell, Book and Candle was designed as a grounded, realistic interior that supports the play’s wit and intimacy while quietly framing its supernatural undercurrents.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90016-gallery-150203.webp",
    "client": "Okoboji Summer Theatre",
    "location": "Okoboji, IA",
    "year": 2025,
    "month": 7,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Bell, Book, and Candle",
    "seoDescription": "Bell, Book and Candle was designed as a grounded, realistic interior that supports the play’s wit and intimacy while quietly framing its supernatural undercurrents. The scenic design focused on creating a believable, mid-century apartment environment with a warm domestic scale and a distinctive green palette that subtly heightened the play’s mood without pushing the space into abstraction.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:01:52.275Z",
    "updatedAt": "2026-02-19T11:01:52.275Z",
    "publishedAt": "2026-02-19T11:01:52.275Z",
    "images": [
      {
        "id": 15,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90016-gallery-150203.webp",
        "altText": "Scenic rendering for Bell, Book, and Candle at Okoboji Summer Theatre. View 1.",
        "caption": "",
        "sortOrder": 6
      }
    ]
  },
  {
    "id": 13,
    "title": "Urinetown",
    "slug": "urinetown",
    "excerpt": "Explore the innovative scenic design of Urinetown, a satirical musical that cleverly tackles a dystopian water shortage. Discover how visuals enhance storytelling!",
    "designNotes": "Scenic rendering series for Urinetown — University of Missouri (2024). This rendering package supports early collaboration by translating concept language into actionable visual cues.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90041-gallery-150082.webp",
    "client": "University of Missouri",
    "location": "Columbia, MO",
    "year": 2024,
    "month": 11,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Urinetown",
    "seoDescription": "Explore the innovative scenic design of Urinetown, a satirical musical that cleverly tackles a dystopian water shortage. Discover how visuals enhance storytelling!",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:01:55.422Z",
    "updatedAt": "2026-02-19T11:01:55.422Z",
    "publishedAt": "2026-02-19T11:01:55.422Z",
    "images": [
      {
        "id": 20,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90041-gallery-150082.webp",
        "altText": "Scenic rendering for Urinetown at University of Missouri. View 3.",
        "caption": "",
        "sortOrder": 0
      },
      {
        "id": 21,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90041-gallery-150120.webp",
        "altText": "Scenic rendering for Urinetown at University of Missouri. View 2.",
        "caption": "",
        "sortOrder": 0
      },
      {
        "id": 22,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90041-gallery-150199.webp",
        "altText": "Scenic rendering for Urinetown at University of Missouri. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 14,
    "title": "Barefoot in the Park",
    "slug": "barefoot-in-the-park",
    "excerpt": "Scenic design for Neil Simon's romantic comedy about newlyweds in a New York City walk-up.",
    "designNotes": "Rendering study for Barefoot in the Park — Okoboji Summer Theatre (2024). The image set is composed to clarify spatial hierarchy, tone, and actor pathways before production execution. Scenic design for Neil Simon's romantic comedy about newlyweds in a New York City walk-up.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90042-gallery-150042.webp",
    "client": "Okoboji Summer Theatre",
    "location": "Okoboji, IA",
    "year": 2024,
    "month": 8,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Barefoot in the Park",
    "seoDescription": "Scenic design for Neil Simon's romantic comedy about newlyweds in a New York City walk-up.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:01:56.363Z",
    "updatedAt": "2026-02-19T11:01:56.363Z",
    "publishedAt": "2026-02-19T11:01:56.363Z",
    "images": [
      {
        "id": 23,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90042-gallery-150042.webp",
        "altText": "Scenic rendering for Barefoot in the Park at Okoboji Summer Theatre. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 18,
    "title": "Head Over Heels",
    "slug": "head-over-heels",
    "excerpt": "Explore the vibrant scenic design of \"Head Over Heels,\" the jukebox musical that celebrates The Go-Go's. Uncover creativity and inspiration behind the stage!",
    "designNotes": "Rendering study for Head Over Heels — Theatre SilCo (2023). The image set is composed to clarify spatial hierarchy, tone, and actor pathways before production execution.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90044-gallery-150090.webp",
    "client": "Theatre SilCo",
    "location": "Silverthorne, CO",
    "year": 2023,
    "month": 6,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Head Over Heels",
    "seoDescription": "Explore the vibrant scenic design of \"Head Over Heels,\" the jukebox musical that celebrates The Go-Go's. Uncover creativity and inspiration behind the stage!",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:02.039Z",
    "updatedAt": "2026-02-19T11:02:02.039Z",
    "publishedAt": "2026-02-19T11:02:02.039Z",
    "images": [
      {
        "id": 41,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90044-gallery-150090.webp",
        "altText": "Scenic rendering for Head Over Heels at Theatre SilCo. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 17,
    "title": "¡LOTERIA: GAME ON!",
    "slug": "loteria-game-on",
    "excerpt": "¡Lotería: Game On! is the world premiere of a bilingual play by Mabelle Reynoso, directed by Sara Rodriguez. The scenic design transforms a familiar suburban basement living room into a vibrant, game-driven world inspired by Lotería, video games, and imaginative play, blending physical scenery, projection, and dynamic lighting to support a fast-moving theatrical experience.",
    "designNotes": "Visualization sequence for ¡LOTERIA: GAME ON! — Theatre SilCo (2023). Renderings are used here as decision tools, aligning scenic intent with directorial storytelling goals. ¡Lotería: Game On! is the world premiere of a bilingual play by Mabelle Reynoso, directed by Sara Rodriguez.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90009-gallery-150191.webp",
    "client": "Theatre SilCo",
    "location": "Silverthorne, CO",
    "year": 2023,
    "month": 3,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "¡LOTERIA: GAME ON!",
    "seoDescription": "¡Lotería: Game On! is the world premiere of a bilingual play by Mabelle Reynoso, directed by Sara Rodriguez. The scenic design transforms a familiar suburban basement living room into a vibrant, game-driven world inspired by Lotería, video games, and imaginative play, blending physical scenery, projection, and dynamic lighting to support a fast-moving theatrical experience.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:00.802Z",
    "updatedAt": "2026-02-19T11:02:00.802Z",
    "publishedAt": "2026-02-19T11:02:00.802Z",
    "images": [
      {
        "id": 39,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90009-gallery-150191.webp",
        "altText": "Scenic rendering for ¡LOTERIA: GAME ON! at Theatre SilCo. View 2.",
        "caption": "",
        "sortOrder": 0
      },
      {
        "id": 40,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90009-gallery-150222.webp",
        "altText": "Scenic rendering for ¡LOTERIA: GAME ON! at Theatre SilCo. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 16,
    "title": "Boeing, Boeing",
    "slug": "boeing-boeing",
    "excerpt": "Scenic design for Marc Camoletti's French farce about an American architect juggling three stewardess fiancées.",
    "designNotes": "Scenic rendering series for Boeing, Boeing — Stephens College (2023). This rendering package supports early collaboration by translating concept language into actionable visual cues. Scenic design for Marc Camoletti's French farce about an American architect juggling three stewardess fiancées.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90054-gallery-150139.webp",
    "client": "Stephens College",
    "location": "Columbia, MO",
    "year": 2023,
    "month": 2,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Boeing, Boeing",
    "seoDescription": "Scenic design for Marc Camoletti's French farce about an American architect juggling three stewardess fiancées.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:01:59.839Z",
    "updatedAt": "2026-02-19T11:01:59.839Z",
    "publishedAt": "2026-02-19T11:01:59.839Z",
    "images": [
      {
        "id": 38,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90054-gallery-150139.webp",
        "altText": "Scenic rendering for Boeing, Boeing at Stephens College. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 20,
    "title": "An Inspector Calls",
    "slug": "an-inspector-calls",
    "excerpt": "Explore the captivating scenic design of J.B. Priestley's \"An Inspector Calls\" and discover how it enhances this gripping moral thriller on class and responsibility.",
    "designNotes": "Concept rendering package for An Inspector Calls — Okoboji Summer Theatre (2022). The visual approach prioritizes atmosphere and material character while maintaining practical scenic readability. B. Priestley's \"An Inspector Calls\" and.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90036-gallery-150134.webp",
    "client": "Okoboji Summer Theatre",
    "location": "Spirit Lake, IA",
    "year": 2022,
    "month": 7,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "An Inspector Calls",
    "seoDescription": "Explore the captivating scenic design of J.B. Priestley's \"An Inspector Calls\" and discover how it enhances this gripping moral thriller on class and responsibility.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:04.334Z",
    "updatedAt": "2026-02-19T11:02:04.334Z",
    "publishedAt": "2026-02-19T11:02:04.334Z",
    "images": [
      {
        "id": 45,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90036-gallery-150134.webp",
        "altText": "Scenic rendering for An Inspector Calls at Okoboji Summer Theatre. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 22,
    "title": "A Funny Thing Happened on the Way to the Forum",
    "slug": "a-funny-thing-happened",
    "excerpt": "Scenic design for the Sondheim musical comedy set in ancient Rome.",
    "designNotes": "Rendering study for A Funny Thing Happened on the Way to the Forum — Lake Dillon Theatre (2022). The image set is composed to clarify spatial hierarchy, tone, and actor pathways before production execution. Scenic design for the Sondheim musical comedy set in ancient Rome.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90049-gallery-150252.webp",
    "client": "Lake Dillon Theatre",
    "location": "Silverthorne, CO",
    "year": 2022,
    "month": 6,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "A Funny Thing Happened on the Way to the Forum",
    "seoDescription": "Scenic design for the Sondheim musical comedy set in ancient Rome.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:06.109Z",
    "updatedAt": "2026-02-19T11:02:06.109Z",
    "publishedAt": "2026-02-19T11:02:06.109Z",
    "images": [
      {
        "id": 47,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90049-gallery-150252.webp",
        "altText": "Scenic rendering for A Funny Thing Happened on the Way to the Forum at Lake Dillon Theatre. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 21,
    "title": "Tomás and the Library Lady",
    "slug": "tomas-and-the-library-lady",
    "excerpt": "Explore the vibrant scenic design of \"Tomás and the Library Lady,\" a bilingual play that celebrates literacy and the transformative power of libraries.",
    "designNotes": "Concept rendering package for Tomás and the Library Lady — Lake Dillon Theatre (2022). The visual approach prioritizes atmosphere and material character while maintaining practical scenic readability.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90039-gallery-150225.webp",
    "client": "Lake Dillon Theatre",
    "location": "Silverthorne, CO",
    "year": 2022,
    "month": 3,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Tomás and the Library Lady",
    "seoDescription": "Explore the vibrant scenic design of \"Tomás and the Library Lady,\" a bilingual play that celebrates literacy and the transformative power of libraries.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:05.210Z",
    "updatedAt": "2026-02-19T11:02:05.210Z",
    "publishedAt": "2026-02-19T11:02:05.210Z",
    "images": [
      {
        "id": 46,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90039-gallery-150225.webp",
        "altText": "Scenic rendering for Tomás and the Library Lady at Lake Dillon Theatre. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 19,
    "title": "The Merry Wives of Windsor",
    "slug": "the-merry-wives-of-windsor",
    "excerpt": "Scenic design for Shakespeare's comedy set in Windsor, England.",
    "designNotes": "Pre-production rendering study for The Merry Wives of Windsor — Stephens College (2022). Each frame is structured to communicate mood, scale, and narrative focus without relying on technical jargon. Scenic design for Shakespeare's comedy set in Windsor, England.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90053-gallery-150015.webp",
    "client": "Stephens College",
    "location": "Columbia, MO",
    "year": 2022,
    "month": 2,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "The Merry Wives of Windsor",
    "seoDescription": "Scenic design for Shakespeare's comedy set in Windsor, England.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:02.980Z",
    "updatedAt": "2026-02-19T11:02:02.980Z",
    "publishedAt": "2026-02-19T11:02:02.980Z",
    "images": [
      {
        "id": 42,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90053-gallery-150015.webp",
        "altText": "Scenic rendering for The Merry Wives of Windsor at Stephens College. View 1.",
        "caption": "",
        "sortOrder": 0
      },
      {
        "id": 43,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90053-gallery-150212.webp",
        "altText": "Scenic rendering for The Merry Wives of Windsor at Stephens College. View 2.",
        "caption": "",
        "sortOrder": 0
      },
      {
        "id": 44,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90053-gallery-150218.webp",
        "altText": "Scenic rendering for The Merry Wives of Windsor at Stephens College. View 3.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 3,
    "title": "Ashes of the Underworld",
    "slug": "ashes-of-the-underworld",
    "excerpt": "A liminal space between life and death, inspired by The Penelopiad. Grecian ruins decay among lifeless trees while fire burns eternal. Created during pandemic isolation in Chicago, when artists found themselves suspended between the theatre that was and whatever might come next.",
    "designNotes": "Ashes of the Underworld is a concept rendering inspired by The Penelopiad, existing in a liminal space between yesterday and tomorrow, life and death, Heaven and Hell. The image depicts Grecian ruins in perpetual decay—crumbling columns stand sentinel among lifeless trees, their skeletal branches reaching toward an uncertain sky. Fire burns eternal in braziers scattered throughout the desolate landscape, casting an otherworldly glow across the rubble-strewn ground.\n\nPenelope sits in quiet contemplation, a solitary figure amid the wreckage of her world, reflecting on choices made and paths not taken. The architecture speaks of glory long past, while the construction materials scattered about suggest a world perpetually building and rebuilding itself, never quite whole.\n\nThis rendering was created during the pandemic in Chicago, a time when artists found themselves in their own liminal space—suspended between the theatre that was and whatever might come next. The isolation of that period found its way into every shadow and every flame, transforming a classical myth into a meditation on artistic exile and the search for creative outlet when all stages had gone dark. Created using Vectorworks for modeling, Twinmotion for rendering, and Photoshop for final atmospheric touches.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/portfolio-images/projects/90013/image-150157.webp",
    "client": "",
    "location": "Chicago, IL",
    "year": 2021,
    "month": null,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Ashes of the Underworld - Scenic Concept by Brandon PT Davis",
    "seoDescription": "Explore 'Ashes of the Underworld,' a haunting scenic concept rendering by Brandon PT Davis, inspired by The Penelopiad and created during pandemic isolation.",
    "seoKeywords": "scenic design,concept rendering,underworld,The Penelopiad,Grecian ruins,experiential design,theatre design,Brandon PT Davis,Chicago,2021",
    "createdAt": "2026-02-19T08:57:56.527Z",
    "updatedAt": "2026-02-19T08:57:56.527Z",
    "publishedAt": "2026-02-19T08:57:56.527Z",
    "images": [
      {
        "id": 11,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771226871303-0012F1AD-66FD-41BD-91E0-34C5B5420FA5_1_105_c-7c0c6217a7.jpg",
        "altText": "Scenic rendering for Ashes of the Underworld in Chicago, IL. View 1.",
        "caption": "",
        "sortOrder": 0
      },
      {
        "id": 12,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771226877260-2960BDC8-FC6F-4701-8E0C-5ADE2F536612_1_105_c-225ea8235b.jpg",
        "altText": "Scenic rendering for Ashes of the Underworld in Chicago, IL. View 2.",
        "caption": "",
        "sortOrder": 1
      },
      {
        "id": 13,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771226885894-D729C095-12C8-469B-8DB5-EA601E086B3C_1_105_c-a45f759a5b.jpg",
        "altText": "Scenic rendering for Ashes of the Underworld in Chicago, IL. View 3.",
        "caption": "",
        "sortOrder": 2
      }
    ]
  },
  {
    "id": 23,
    "title": "The Penelopiad",
    "slug": "the-penelopiad",
    "excerpt": "Explore the innovative scenic design of Margaret Atwood's The Penelopiad, a captivating retelling of The Odyssey from Penelope's unique perspective.",
    "designNotes": "Visualization sequence for The Penelopiad — University of California Irvine (2020). Renderings are used here as decision tools, aligning scenic intent with directorial storytelling goals.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90051-gallery-150154.webp",
    "client": "University of California Irvine",
    "location": "Irvine, CA",
    "year": 2020,
    "month": 2,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "The Penelopiad",
    "seoDescription": "Explore the innovative scenic design of Margaret Atwood's The Penelopiad, a captivating retelling of The Odyssey from Penelope's unique perspective.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:06.954Z",
    "updatedAt": "2026-02-19T11:02:06.954Z",
    "publishedAt": "2026-02-19T11:02:06.954Z",
    "images": [
      {
        "id": 48,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90051-gallery-150154.webp",
        "altText": "Scenic rendering for The Penelopiad at University of California Irvine. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 1,
    "title": "Isolation",
    "slug": "isolation",
    "excerpt": "Set in a quiet, imagined interior, this rendering explores themes of isolation, distance, and the weight of solitude. A contemplative space where architecture becomes emotion, and emptiness speaks volumes.",
    "designNotes": "Scenic rendering series for Isolation — (2020). This rendering package supports early collaboration by translating concept language into actionable visual cues. Set in a quiet, imagined interior, this rendering explores themes of isolation, distance, and the weight of solitude.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90015-gallery-150098.webp",
    "client": "",
    "location": "Chicago, IL",
    "year": 2020,
    "month": null,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Isolation - Experiential Scenic Design by Brandon PT Davis",
    "seoDescription": "Explore 'Isolation,' a contemplative rendering by Brandon PT Davis. This independent project from 2020 delves into themes of solitude and emotional architecture.",
    "seoKeywords": "Isolation,scenic design,experiential design,rendering,Brandon PT Davis,solitude,interior design",
    "createdAt": "2026-02-19T08:57:55.493Z",
    "updatedAt": "2026-02-19T08:57:55.493Z",
    "publishedAt": "2026-02-19T08:57:55.493Z",
    "images": []
  },
  {
    "id": 26,
    "title": "Company",
    "slug": "company",
    "excerpt": "Explore the captivating scenic design of Sondheim's musical, showcasing the complexities of marriage and relationships in vibrant New York City.",
    "designNotes": "Scenic rendering series for Company — University of California Irvine (2019). This rendering package supports early collaboration by translating concept language into actionable visual cues.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90019-gallery-150102.webp",
    "client": "University of California Irvine",
    "location": "Irvine, CA",
    "year": 2019,
    "month": 11,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Company",
    "seoDescription": "Explore the captivating scenic design of Sondheim's musical, showcasing the complexities of marriage and relationships in vibrant New York City.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:09.677Z",
    "updatedAt": "2026-02-19T11:02:09.677Z",
    "publishedAt": "2026-02-19T11:02:09.677Z",
    "images": [
      {
        "id": 56,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90019-gallery-150102.webp",
        "altText": "Scenic rendering for Company at University of California Irvine. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 24,
    "title": "Parliament Square",
    "slug": "parliament-square",
    "excerpt": "Explore the stunning theatrical and scenic design of Parliament Square. Discover its history, artistry, and how it enhances the cultural landscape.",
    "designNotes": "Pre-production rendering study for Parliament Square — University of California Irvine (2019). Each frame is structured to communicate mood, scale, and narrative focus without relying on technical jargon.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90018-gallery-150241.webp",
    "client": "University of California Irvine",
    "location": "Irvine, CA",
    "year": 2019,
    "month": 2,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Parliament Square",
    "seoDescription": "Explore the stunning theatrical and scenic design of Parliament Square. Discover its history, artistry, and how it enhances the cultural landscape.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:07.697Z",
    "updatedAt": "2026-02-19T11:02:07.697Z",
    "publishedAt": "2026-02-19T11:02:07.697Z",
    "images": [
      {
        "id": 49,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90018-gallery-150241.webp",
        "altText": "Scenic rendering for Parliament Square at University of California Irvine. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 27,
    "title": "American Idiot",
    "slug": "american-idiot",
    "excerpt": "Explore the stunning scenic design of the Green Day rock musical \"American Idiot.\" Discover how innovative visuals enhance this powerful theatrical experience.",
    "designNotes": "Image set for American Idiot — University of California Irvine (2018). The work balances emotional atmosphere with stage logic, helping teams evaluate ideas before they are built. \".",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90038-gallery-150176.webp",
    "client": "University of California Irvine",
    "location": "Irvine, CA",
    "year": 2018,
    "month": 6,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "American Idiot",
    "seoDescription": "Explore the stunning scenic design of the Green Day rock musical \"American Idiot.\" Discover how innovative visuals enhance this powerful theatrical experience.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:10.332Z",
    "updatedAt": "2026-02-19T11:02:10.332Z",
    "publishedAt": "2026-02-19T11:02:10.332Z",
    "images": [
      {
        "id": 57,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90038-gallery-150176.webp",
        "altText": "Scenic rendering for American Idiot at University of California Irvine. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 4,
    "title": "Angel Food Cake",
    "slug": "angel-food-cake",
    "excerpt": "A mobile home interior for the West Coast premiere of Angel Food Cake at Western Summer Theatre. Plaid upholstery, red-checkered backsplash, wood-paneled walls—everyday space holding extraordinary emotional weight. The home itself becomes a character.",
    "designNotes": "Scenic rendering series for Angel Food Cake — Western Summer Theatre (2017). This rendering package supports early collaboration by translating concept language into actionable visual cues. A mobile home interior for the West Coast premiere of Angel Food Cake at Western Summer Theatre.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90014-gallery-150055.webp",
    "client": "Western Summer Theatre",
    "location": "Bellingham, WA",
    "year": 2017,
    "month": null,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Angel Food Cake - Scenic Rendering by Brandon PT Davis",
    "seoDescription": "Explore Brandon PT Davis's scenic rendering for the West Coast premiere of 'Angel Food Cake' at Western Summer Theatre. A detailed mobile home interior design.",
    "seoKeywords": "scenic design,rendering,Angel Food Cake,theatre,Brandon PT Davis,mobile home,set design",
    "createdAt": "2026-02-19T08:57:57.060Z",
    "updatedAt": "2026-02-19T08:57:57.060Z",
    "publishedAt": "2026-02-19T08:57:57.060Z",
    "images": []
  },
  {
    "id": 28,
    "title": "Angel Street",
    "slug": "angel-street",
    "excerpt": "Explore the captivating scenic design of \"Angel Street,\" Patrick Hamilton's Victorian thriller. Discover how visual elements enhance this gripping Gaslight tale!",
    "designNotes": "Visualization sequence for Angel Street — Okoboji Summer Theatre (2013). Renderings are used here as decision tools, aligning scenic intent with directorial storytelling goals.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90043-gallery-150234.webp",
    "client": "Okoboji Summer Theatre",
    "location": "Columbia, MO",
    "year": 2013,
    "month": 7,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "Angel Street",
    "seoDescription": "Explore the captivating scenic design of \"Angel Street,\" Patrick Hamilton's Victorian thriller. Discover how visual elements enhance this gripping Gaslight tale!",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:11.145Z",
    "updatedAt": "2026-02-19T11:02:11.145Z",
    "publishedAt": "2026-02-19T11:02:11.145Z",
    "images": [
      {
        "id": 58,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90043-gallery-150234.webp",
        "altText": "Scenic rendering for Angel Street at Okoboji Summer Theatre. View 1.",
        "caption": "",
        "sortOrder": 0
      }
    ]
  },
  {
    "id": 29,
    "title": "All My Sons",
    "slug": "all-my-sons",
    "excerpt": "All My Sons is set in a postwar suburban world that appears stable, orderly, and complete. The scenic design centers on a modest family home with an open porch and backyard, creating a familiar environment shaped by optimism and routine.",
    "designNotes": "Image set for All My Sons — Stephens College (2010). The work balances emotional atmosphere with stage logic, helping teams evaluate ideas before they are built. All My Sons is set in a postwar suburban world that appears stable, orderly, and complete.",
    "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90017-gallery-150073.webp",
    "client": "Stephens College",
    "location": "Columbia, MO",
    "year": 2010,
    "month": 10,
    "status": "published",
    "featured": false,
    "galleryOnly": false,
    "seoTitle": "All My Sons",
    "seoDescription": "All My Sons is set in a postwar suburban world that appears stable, orderly, and complete. The scenic design centers on a modest family home with an open porch and backyard, creating a familiar environment shaped by optimism and routine.",
    "seoKeywords": null,
    "createdAt": "2026-02-19T11:02:11.768Z",
    "updatedAt": "2026-02-19T11:02:11.768Z",
    "publishedAt": "2026-02-19T11:02:11.768Z",
    "images": [
      {
        "id": 59,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90017-gallery-150073.webp",
        "altText": "Scenic rendering for All My Sons at Stephens College. View 1.",
        "caption": "",
        "sortOrder": 7
      }
    ]
  }
];

export const generatedRenderingGallery = [
  {
    "id": 31,
    "altText": "Scenic rendering for The Glass Menagerie at Maples Repertory Theatre. View 1.",
    "displayTitle": "The Glass Menagerie",
    "description": "",
    "sortOrder": 10,
    "active": true,
    "projectId": 9,
    "project": {
      "id": 9,
      "title": "The Glass Menagerie",
      "slug": "the-glass-menagerie",
      "excerpt": "The Glass Menagerie at Maples Repertory Theatre, directed by Kimberly Braun, was staged as a memory play shaped by Tom Wingfield’s recollection rather than a literal apartment. The scenic environment emphasized fluid movement and emotional geography, supporting the play’s themes of longing, confinement, and escape.\n",
      "designNotes": "Visualization sequence for The Glass Menagerie — Maples Repertory Theatre (2025). Renderings are used here as decision tools, aligning scenic intent with directorial storytelling goals. The Glass Menagerie at Maples Repertory Theatre, directed by Kimberly Braun, was staged as a memory play shaped by Tom Wingfield’s recollection rather than a literal apartment.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90010-gallery-150168.webp",
      "client": "Maples Repertory Theatre",
      "location": " Macon, MO",
      "year": 2025,
      "month": 10,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "The Glass Menagerie",
      "seoDescription": "The Glass Menagerie at Maples Repertory Theatre, directed by Kimberly Braun, was staged as a memory play shaped by Tom Wingfield’s recollection rather than a literal apartment. The scenic environment emphasized fluid movement and emotional geography, supporting the play’s themes of longing, confinement, and escape.\n",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:01:51.231Z",
      "updatedAt": "2026-02-19T11:01:51.231Z",
      "publishedAt": "2026-02-19T11:01:51.231Z",
      "images": [
        {
          "id": 14,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90010-gallery-150168.webp",
          "altText": "Scenic rendering for The Glass Menagerie at Maples Repertory Theatre. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 32,
    "altText": "Scenic rendering for Bell, Book, and Candle at Okoboji Summer Theatre. View 1.",
    "displayTitle": "Bell, Book, and Candle",
    "description": "",
    "sortOrder": 11,
    "active": true,
    "projectId": 10,
    "project": {
      "id": 10,
      "title": "Bell, Book, and Candle",
      "slug": "bell-book-and-candle",
      "excerpt": "Bell, Book and Candle was designed as a grounded, realistic interior that supports the play’s wit and intimacy while quietly framing its supernatural undercurrents. The scenic design focused on creating a believable, mid-century apartment environment with a warm domestic scale and a distinctive green palette that subtly heightened the play’s mood without pushing the space into abstraction.",
      "designNotes": "Scenic rendering series for Bell, Book, and Candle — Okoboji Summer Theatre (2025). This rendering package supports early collaboration by translating concept language into actionable visual cues. Bell, Book and Candle was designed as a grounded, realistic interior that supports the play’s wit and intimacy while quietly framing its supernatural undercurrents.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90016-gallery-150203.webp",
      "client": "Okoboji Summer Theatre",
      "location": "Okoboji, IA",
      "year": 2025,
      "month": 7,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "Bell, Book, and Candle",
      "seoDescription": "Bell, Book and Candle was designed as a grounded, realistic interior that supports the play’s wit and intimacy while quietly framing its supernatural undercurrents. The scenic design focused on creating a believable, mid-century apartment environment with a warm domestic scale and a distinctive green palette that subtly heightened the play’s mood without pushing the space into abstraction.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:01:52.275Z",
      "updatedAt": "2026-02-19T11:01:52.275Z",
      "publishedAt": "2026-02-19T11:01:52.275Z",
      "images": [
        {
          "id": 15,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90016-gallery-150203.webp",
          "altText": "Scenic rendering for Bell, Book, and Candle at Okoboji Summer Theatre. View 1.",
          "caption": "",
          "sortOrder": 6
        }
      ]
    }
  },
  {
    "id": 35,
    "altText": "Scenic rendering for Urinetown at University of Missouri. View 1.",
    "displayTitle": "Urinetown",
    "description": "",
    "sortOrder": 14,
    "active": true,
    "projectId": 13,
    "project": {
      "id": 13,
      "title": "Urinetown",
      "slug": "urinetown",
      "excerpt": "Explore the innovative scenic design of Urinetown, a satirical musical that cleverly tackles a dystopian water shortage. Discover how visuals enhance storytelling!",
      "designNotes": "Scenic rendering series for Urinetown — University of Missouri (2024). This rendering package supports early collaboration by translating concept language into actionable visual cues.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90041-gallery-150082.webp",
      "client": "University of Missouri",
      "location": "Columbia, MO",
      "year": 2024,
      "month": 11,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "Urinetown",
      "seoDescription": "Explore the innovative scenic design of Urinetown, a satirical musical that cleverly tackles a dystopian water shortage. Discover how visuals enhance storytelling!",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:01:55.422Z",
      "updatedAt": "2026-02-19T11:01:55.422Z",
      "publishedAt": "2026-02-19T11:01:55.422Z",
      "images": [
        {
          "id": 20,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90041-gallery-150082.webp",
          "altText": "Scenic rendering for Urinetown at University of Missouri. View 3.",
          "caption": "",
          "sortOrder": 0
        },
        {
          "id": 21,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90041-gallery-150120.webp",
          "altText": "Scenic rendering for Urinetown at University of Missouri. View 2.",
          "caption": "",
          "sortOrder": 0
        },
        {
          "id": 22,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90041-gallery-150199.webp",
          "altText": "Scenic rendering for Urinetown at University of Missouri. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 36,
    "altText": "Scenic rendering for Barefoot in the Park at Okoboji Summer Theatre. View 1.",
    "displayTitle": "Barefoot in the Park",
    "description": "",
    "sortOrder": 15,
    "active": true,
    "projectId": 14,
    "project": {
      "id": 14,
      "title": "Barefoot in the Park",
      "slug": "barefoot-in-the-park",
      "excerpt": "Scenic design for Neil Simon's romantic comedy about newlyweds in a New York City walk-up.",
      "designNotes": "Rendering study for Barefoot in the Park — Okoboji Summer Theatre (2024). The image set is composed to clarify spatial hierarchy, tone, and actor pathways before production execution. Scenic design for Neil Simon's romantic comedy about newlyweds in a New York City walk-up.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90042-gallery-150042.webp",
      "client": "Okoboji Summer Theatre",
      "location": "Okoboji, IA",
      "year": 2024,
      "month": 8,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "Barefoot in the Park",
      "seoDescription": "Scenic design for Neil Simon's romantic comedy about newlyweds in a New York City walk-up.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:01:56.363Z",
      "updatedAt": "2026-02-19T11:01:56.363Z",
      "publishedAt": "2026-02-19T11:01:56.363Z",
      "images": [
        {
          "id": 23,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90042-gallery-150042.webp",
          "altText": "Scenic rendering for Barefoot in the Park at Okoboji Summer Theatre. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 38,
    "altText": "Scenic rendering for Boeing, Boeing at Stephens College. View 1.",
    "displayTitle": "Boeing, Boeing",
    "description": "",
    "sortOrder": 17,
    "active": true,
    "projectId": 16,
    "project": {
      "id": 16,
      "title": "Boeing, Boeing",
      "slug": "boeing-boeing",
      "excerpt": "Scenic design for Marc Camoletti's French farce about an American architect juggling three stewardess fiancées.",
      "designNotes": "Scenic rendering series for Boeing, Boeing — Stephens College (2023). This rendering package supports early collaboration by translating concept language into actionable visual cues. Scenic design for Marc Camoletti's French farce about an American architect juggling three stewardess fiancées.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90054-gallery-150139.webp",
      "client": "Stephens College",
      "location": "Columbia, MO",
      "year": 2023,
      "month": 2,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "Boeing, Boeing",
      "seoDescription": "Scenic design for Marc Camoletti's French farce about an American architect juggling three stewardess fiancées.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:01:59.839Z",
      "updatedAt": "2026-02-19T11:01:59.839Z",
      "publishedAt": "2026-02-19T11:01:59.839Z",
      "images": [
        {
          "id": 38,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90054-gallery-150139.webp",
          "altText": "Scenic rendering for Boeing, Boeing at Stephens College. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 39,
    "altText": "Scenic rendering for ¡LOTERIA: GAME ON! at Theatre SilCo. View 1.",
    "displayTitle": "¡LOTERIA: GAME ON!",
    "description": "",
    "sortOrder": 18,
    "active": true,
    "projectId": 17,
    "project": {
      "id": 17,
      "title": "¡LOTERIA: GAME ON!",
      "slug": "loteria-game-on",
      "excerpt": "¡Lotería: Game On! is the world premiere of a bilingual play by Mabelle Reynoso, directed by Sara Rodriguez. The scenic design transforms a familiar suburban basement living room into a vibrant, game-driven world inspired by Lotería, video games, and imaginative play, blending physical scenery, projection, and dynamic lighting to support a fast-moving theatrical experience.",
      "designNotes": "Visualization sequence for ¡LOTERIA: GAME ON! — Theatre SilCo (2023). Renderings are used here as decision tools, aligning scenic intent with directorial storytelling goals. ¡Lotería: Game On! is the world premiere of a bilingual play by Mabelle Reynoso, directed by Sara Rodriguez.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90009-gallery-150191.webp",
      "client": "Theatre SilCo",
      "location": "Silverthorne, CO",
      "year": 2023,
      "month": 3,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "¡LOTERIA: GAME ON!",
      "seoDescription": "¡Lotería: Game On! is the world premiere of a bilingual play by Mabelle Reynoso, directed by Sara Rodriguez. The scenic design transforms a familiar suburban basement living room into a vibrant, game-driven world inspired by Lotería, video games, and imaginative play, blending physical scenery, projection, and dynamic lighting to support a fast-moving theatrical experience.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:00.802Z",
      "updatedAt": "2026-02-19T11:02:00.802Z",
      "publishedAt": "2026-02-19T11:02:00.802Z",
      "images": [
        {
          "id": 39,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90009-gallery-150191.webp",
          "altText": "Scenic rendering for ¡LOTERIA: GAME ON! at Theatre SilCo. View 2.",
          "caption": "",
          "sortOrder": 0
        },
        {
          "id": 40,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90009-gallery-150222.webp",
          "altText": "Scenic rendering for ¡LOTERIA: GAME ON! at Theatre SilCo. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 40,
    "altText": "Scenic rendering for Head Over Heels at Theatre SilCo. View 1.",
    "displayTitle": "Head Over Heels",
    "description": "",
    "sortOrder": 19,
    "active": true,
    "projectId": 18,
    "project": {
      "id": 18,
      "title": "Head Over Heels",
      "slug": "head-over-heels",
      "excerpt": "Explore the vibrant scenic design of \"Head Over Heels,\" the jukebox musical that celebrates The Go-Go's. Uncover creativity and inspiration behind the stage!",
      "designNotes": "Rendering study for Head Over Heels — Theatre SilCo (2023). The image set is composed to clarify spatial hierarchy, tone, and actor pathways before production execution.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90044-gallery-150090.webp",
      "client": "Theatre SilCo",
      "location": "Silverthorne, CO",
      "year": 2023,
      "month": 6,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "Head Over Heels",
      "seoDescription": "Explore the vibrant scenic design of \"Head Over Heels,\" the jukebox musical that celebrates The Go-Go's. Uncover creativity and inspiration behind the stage!",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:02.039Z",
      "updatedAt": "2026-02-19T11:02:02.039Z",
      "publishedAt": "2026-02-19T11:02:02.039Z",
      "images": [
        {
          "id": 41,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90044-gallery-150090.webp",
          "altText": "Scenic rendering for Head Over Heels at Theatre SilCo. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 41,
    "altText": "Scenic rendering for The Merry Wives of Windsor at Stephens College. View 1.",
    "displayTitle": "The Merry Wives of Windsor",
    "description": "",
    "sortOrder": 20,
    "active": true,
    "projectId": 19,
    "project": {
      "id": 19,
      "title": "The Merry Wives of Windsor",
      "slug": "the-merry-wives-of-windsor",
      "excerpt": "Scenic design for Shakespeare's comedy set in Windsor, England.",
      "designNotes": "Pre-production rendering study for The Merry Wives of Windsor — Stephens College (2022). Each frame is structured to communicate mood, scale, and narrative focus without relying on technical jargon. Scenic design for Shakespeare's comedy set in Windsor, England.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90053-gallery-150015.webp",
      "client": "Stephens College",
      "location": "Columbia, MO",
      "year": 2022,
      "month": 2,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "The Merry Wives of Windsor",
      "seoDescription": "Scenic design for Shakespeare's comedy set in Windsor, England.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:02.980Z",
      "updatedAt": "2026-02-19T11:02:02.980Z",
      "publishedAt": "2026-02-19T11:02:02.980Z",
      "images": [
        {
          "id": 42,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90053-gallery-150015.webp",
          "altText": "Scenic rendering for The Merry Wives of Windsor at Stephens College. View 1.",
          "caption": "",
          "sortOrder": 0
        },
        {
          "id": 43,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90053-gallery-150212.webp",
          "altText": "Scenic rendering for The Merry Wives of Windsor at Stephens College. View 2.",
          "caption": "",
          "sortOrder": 0
        },
        {
          "id": 44,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90053-gallery-150218.webp",
          "altText": "Scenic rendering for The Merry Wives of Windsor at Stephens College. View 3.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 42,
    "altText": "Scenic rendering for An Inspector Calls at Okoboji Summer Theatre. View 1.",
    "displayTitle": "An Inspector Calls",
    "description": "",
    "sortOrder": 21,
    "active": true,
    "projectId": 20,
    "project": {
      "id": 20,
      "title": "An Inspector Calls",
      "slug": "an-inspector-calls",
      "excerpt": "Explore the captivating scenic design of J.B. Priestley's \"An Inspector Calls\" and discover how it enhances this gripping moral thriller on class and responsibility.",
      "designNotes": "Concept rendering package for An Inspector Calls — Okoboji Summer Theatre (2022). The visual approach prioritizes atmosphere and material character while maintaining practical scenic readability. B. Priestley's \"An Inspector Calls\" and.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90036-gallery-150134.webp",
      "client": "Okoboji Summer Theatre",
      "location": "Spirit Lake, IA",
      "year": 2022,
      "month": 7,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "An Inspector Calls",
      "seoDescription": "Explore the captivating scenic design of J.B. Priestley's \"An Inspector Calls\" and discover how it enhances this gripping moral thriller on class and responsibility.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:04.334Z",
      "updatedAt": "2026-02-19T11:02:04.334Z",
      "publishedAt": "2026-02-19T11:02:04.334Z",
      "images": [
        {
          "id": 45,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90036-gallery-150134.webp",
          "altText": "Scenic rendering for An Inspector Calls at Okoboji Summer Theatre. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 43,
    "altText": "Scenic rendering for Tomás and the Library Lady at Lake Dillon Theatre. View 1.",
    "displayTitle": "Tomás and the Library Lady",
    "description": "",
    "sortOrder": 22,
    "active": true,
    "projectId": 21,
    "project": {
      "id": 21,
      "title": "Tomás and the Library Lady",
      "slug": "tomas-and-the-library-lady",
      "excerpt": "Explore the vibrant scenic design of \"Tomás and the Library Lady,\" a bilingual play that celebrates literacy and the transformative power of libraries.",
      "designNotes": "Concept rendering package for Tomás and the Library Lady — Lake Dillon Theatre (2022). The visual approach prioritizes atmosphere and material character while maintaining practical scenic readability.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90039-gallery-150225.webp",
      "client": "Lake Dillon Theatre",
      "location": "Silverthorne, CO",
      "year": 2022,
      "month": 3,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "Tomás and the Library Lady",
      "seoDescription": "Explore the vibrant scenic design of \"Tomás and the Library Lady,\" a bilingual play that celebrates literacy and the transformative power of libraries.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:05.210Z",
      "updatedAt": "2026-02-19T11:02:05.210Z",
      "publishedAt": "2026-02-19T11:02:05.210Z",
      "images": [
        {
          "id": 46,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90039-gallery-150225.webp",
          "altText": "Scenic rendering for Tomás and the Library Lady at Lake Dillon Theatre. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 44,
    "altText": "Scenic rendering for A Funny Thing Happened on the Way to the Forum at Lake Dillon Theatre. View 1.",
    "displayTitle": "A Funny Thing Happened on the Way to the Forum",
    "description": "",
    "sortOrder": 23,
    "active": true,
    "projectId": 22,
    "project": {
      "id": 22,
      "title": "A Funny Thing Happened on the Way to the Forum",
      "slug": "a-funny-thing-happened",
      "excerpt": "Scenic design for the Sondheim musical comedy set in ancient Rome.",
      "designNotes": "Rendering study for A Funny Thing Happened on the Way to the Forum — Lake Dillon Theatre (2022). The image set is composed to clarify spatial hierarchy, tone, and actor pathways before production execution. Scenic design for the Sondheim musical comedy set in ancient Rome.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90049-gallery-150252.webp",
      "client": "Lake Dillon Theatre",
      "location": "Silverthorne, CO",
      "year": 2022,
      "month": 6,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "A Funny Thing Happened on the Way to the Forum",
      "seoDescription": "Scenic design for the Sondheim musical comedy set in ancient Rome.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:06.109Z",
      "updatedAt": "2026-02-19T11:02:06.109Z",
      "publishedAt": "2026-02-19T11:02:06.109Z",
      "images": [
        {
          "id": 47,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90049-gallery-150252.webp",
          "altText": "Scenic rendering for A Funny Thing Happened on the Way to the Forum at Lake Dillon Theatre. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 45,
    "altText": "Scenic rendering for The Penelopiad at University of California Irvine. View 1.",
    "displayTitle": "The Penelopiad",
    "description": "",
    "sortOrder": 24,
    "active": true,
    "projectId": 23,
    "project": {
      "id": 23,
      "title": "The Penelopiad",
      "slug": "the-penelopiad",
      "excerpt": "Explore the innovative scenic design of Margaret Atwood's The Penelopiad, a captivating retelling of The Odyssey from Penelope's unique perspective.",
      "designNotes": "Visualization sequence for The Penelopiad — University of California Irvine (2020). Renderings are used here as decision tools, aligning scenic intent with directorial storytelling goals.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90051-gallery-150154.webp",
      "client": "University of California Irvine",
      "location": "Irvine, CA",
      "year": 2020,
      "month": 2,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "The Penelopiad",
      "seoDescription": "Explore the innovative scenic design of Margaret Atwood's The Penelopiad, a captivating retelling of The Odyssey from Penelope's unique perspective.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:06.954Z",
      "updatedAt": "2026-02-19T11:02:06.954Z",
      "publishedAt": "2026-02-19T11:02:06.954Z",
      "images": [
        {
          "id": 48,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90051-gallery-150154.webp",
          "altText": "Scenic rendering for The Penelopiad at University of California Irvine. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 46,
    "altText": "Scenic rendering for Parliament Square at University of California Irvine. View 1.",
    "displayTitle": "Parliament Square",
    "description": "",
    "sortOrder": 25,
    "active": true,
    "projectId": 24,
    "project": {
      "id": 24,
      "title": "Parliament Square",
      "slug": "parliament-square",
      "excerpt": "Explore the stunning theatrical and scenic design of Parliament Square. Discover its history, artistry, and how it enhances the cultural landscape.",
      "designNotes": "Pre-production rendering study for Parliament Square — University of California Irvine (2019). Each frame is structured to communicate mood, scale, and narrative focus without relying on technical jargon.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90018-gallery-150241.webp",
      "client": "University of California Irvine",
      "location": "Irvine, CA",
      "year": 2019,
      "month": 2,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "Parliament Square",
      "seoDescription": "Explore the stunning theatrical and scenic design of Parliament Square. Discover its history, artistry, and how it enhances the cultural landscape.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:07.697Z",
      "updatedAt": "2026-02-19T11:02:07.697Z",
      "publishedAt": "2026-02-19T11:02:07.697Z",
      "images": [
        {
          "id": 49,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90018-gallery-150241.webp",
          "altText": "Scenic rendering for Parliament Square at University of California Irvine. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 48,
    "altText": "Scenic rendering for Company at University of California Irvine. View 1.",
    "displayTitle": "Company",
    "description": "",
    "sortOrder": 27,
    "active": true,
    "projectId": 26,
    "project": {
      "id": 26,
      "title": "Company",
      "slug": "company",
      "excerpt": "Explore the captivating scenic design of Sondheim's musical, showcasing the complexities of marriage and relationships in vibrant New York City.",
      "designNotes": "Scenic rendering series for Company — University of California Irvine (2019). This rendering package supports early collaboration by translating concept language into actionable visual cues.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90019-gallery-150102.webp",
      "client": "University of California Irvine",
      "location": "Irvine, CA",
      "year": 2019,
      "month": 11,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "Company",
      "seoDescription": "Explore the captivating scenic design of Sondheim's musical, showcasing the complexities of marriage and relationships in vibrant New York City.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:09.677Z",
      "updatedAt": "2026-02-19T11:02:09.677Z",
      "publishedAt": "2026-02-19T11:02:09.677Z",
      "images": [
        {
          "id": 56,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90019-gallery-150102.webp",
          "altText": "Scenic rendering for Company at University of California Irvine. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 49,
    "altText": "Scenic rendering for American Idiot at University of California Irvine. View 1.",
    "displayTitle": "American Idiot",
    "description": "",
    "sortOrder": 28,
    "active": true,
    "projectId": 27,
    "project": {
      "id": 27,
      "title": "American Idiot",
      "slug": "american-idiot",
      "excerpt": "Explore the stunning scenic design of the Green Day rock musical \"American Idiot.\" Discover how innovative visuals enhance this powerful theatrical experience.",
      "designNotes": "Image set for American Idiot — University of California Irvine (2018). The work balances emotional atmosphere with stage logic, helping teams evaluate ideas before they are built. \".",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90038-gallery-150176.webp",
      "client": "University of California Irvine",
      "location": "Irvine, CA",
      "year": 2018,
      "month": 6,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "American Idiot",
      "seoDescription": "Explore the stunning scenic design of the Green Day rock musical \"American Idiot.\" Discover how innovative visuals enhance this powerful theatrical experience.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:10.332Z",
      "updatedAt": "2026-02-19T11:02:10.332Z",
      "publishedAt": "2026-02-19T11:02:10.332Z",
      "images": [
        {
          "id": 57,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90038-gallery-150176.webp",
          "altText": "Scenic rendering for American Idiot at University of California Irvine. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 50,
    "altText": "Scenic rendering for Angel Street at Okoboji Summer Theatre. View 1.",
    "displayTitle": "Angel Street",
    "description": "",
    "sortOrder": 29,
    "active": true,
    "projectId": 28,
    "project": {
      "id": 28,
      "title": "Angel Street",
      "slug": "angel-street",
      "excerpt": "Explore the captivating scenic design of \"Angel Street,\" Patrick Hamilton's Victorian thriller. Discover how visual elements enhance this gripping Gaslight tale!",
      "designNotes": "Visualization sequence for Angel Street — Okoboji Summer Theatre (2013). Renderings are used here as decision tools, aligning scenic intent with directorial storytelling goals.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90043-gallery-150234.webp",
      "client": "Okoboji Summer Theatre",
      "location": "Columbia, MO",
      "year": 2013,
      "month": 7,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "Angel Street",
      "seoDescription": "Explore the captivating scenic design of \"Angel Street,\" Patrick Hamilton's Victorian thriller. Discover how visual elements enhance this gripping Gaslight tale!",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:11.145Z",
      "updatedAt": "2026-02-19T11:02:11.145Z",
      "publishedAt": "2026-02-19T11:02:11.145Z",
      "images": [
        {
          "id": 58,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90043-gallery-150234.webp",
          "altText": "Scenic rendering for Angel Street at Okoboji Summer Theatre. View 1.",
          "caption": "",
          "sortOrder": 0
        }
      ]
    }
  },
  {
    "id": 51,
    "altText": "Scenic rendering for All My Sons at Stephens College. View 1.",
    "displayTitle": "All My Sons",
    "description": "",
    "sortOrder": 30,
    "active": true,
    "projectId": 29,
    "project": {
      "id": 29,
      "title": "All My Sons",
      "slug": "all-my-sons",
      "excerpt": "All My Sons is set in a postwar suburban world that appears stable, orderly, and complete. The scenic design centers on a modest family home with an open porch and backyard, creating a familiar environment shaped by optimism and routine.",
      "designNotes": "Image set for All My Sons — Stephens College (2010). The work balances emotional atmosphere with stage logic, helping teams evaluate ideas before they are built. All My Sons is set in a postwar suburban world that appears stable, orderly, and complete.",
      "coverImageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90017-gallery-150073.webp",
      "client": "Stephens College",
      "location": "Columbia, MO",
      "year": 2010,
      "month": 10,
      "status": "published",
      "featured": false,
      "galleryOnly": false,
      "seoTitle": "All My Sons",
      "seoDescription": "All My Sons is set in a postwar suburban world that appears stable, orderly, and complete. The scenic design centers on a modest family home with an open porch and backyard, creating a familiar environment shaped by optimism and routine.",
      "seoKeywords": null,
      "createdAt": "2026-02-19T11:02:11.768Z",
      "updatedAt": "2026-02-19T11:02:11.768Z",
      "publishedAt": "2026-02-19T11:02:11.768Z",
      "images": [
        {
          "id": 59,
          "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/project-90017-gallery-150073.webp",
          "altText": "Scenic rendering for All My Sons at Stephens College. View 1.",
          "caption": "",
          "sortOrder": 7
        }
      ]
    }
  }
];

export const generatedExperientialProcessGallery = [
  {
    "id": 3,
    "category": "live-events",
    "imageUrl": "",
    "videoUrl": "https://youtu.be/qI5cri-yUMg",
    "altText": "",
    "displayTitle": "First Bank Lollipops Commercial",
    "description": "",
    "sortOrder": 1,
    "active": true,
    "projectId": null,
    "year": null,
    "createdAt": "2026-02-16T07:09:27.104Z",
    "images": []
  },
  {
    "id": 12,
    "category": "live-events",
    "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/experiential-process/live-events/1771290240875-toyota-gold-cup-final-29.png",
    "videoUrl": null,
    "altText": "",
    "displayTitle": "Toyota Gold Cup Final 29",
    "description": "",
    "sortOrder": 2,
    "active": true,
    "projectId": 9,
    "year": 2025,
    "createdAt": "2026-02-17T01:04:03.540Z",
    "images": [
      {
        "id": 110,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771290461111-Toyota-Gold-Cup-Final-29-271bdafcb3.png",
        "videoUrl": null,
        "altText": "Toyota Gold Cup Final 29 scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      },
      {
        "id": 107,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771290350722-Screenshot-2026-01-12-at-1.15.34-PM-Large-3fe1d90b43.jpg",
        "videoUrl": null,
        "altText": "Scenic rendering for Toyota Gold Cup Final 29 with event-scale composition, scenic design by Brandon PT Davis.",
        "caption": "",
        "title": "",
        "sortOrder": 1,
        "imageType": "rendering"
      },
      {
        "id": 108,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771290353280-Screenshot-2026-01-12-at-1.16.08-PM-Large-338452b69d.jpg",
        "videoUrl": null,
        "altText": "Rendering variation for Toyota Gold Cup Final 29 exploring layout and sightlines, scenic design by Brandon PT Davis.",
        "caption": "",
        "title": "",
        "sortOrder": 2,
        "imageType": "rendering"
      },
      {
        "id": 109,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771290358832-Screenshot-2026-01-12-at-1.17.01-PM-Large-c69eb3f5ac.jpg",
        "videoUrl": null,
        "altText": "Concept rendering view for Toyota Gold Cup Final 29, scenic design by Brandon PT Davis.",
        "caption": "",
        "title": "",
        "sortOrder": 3,
        "imageType": "rendering"
      }
    ]
  },
  {
    "id": 6,
    "category": "rendering",
    "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/experiential-process/rendering/1771226600321-96246012-2a71-42d9-85e2-77e5d3bafaae_1_105_c.webp",
    "videoUrl": null,
    "altText": "",
    "displayTitle": "Red Line Cafe",
    "description": "",
    "sortOrder": 4,
    "active": true,
    "projectId": 3,
    "year": 2025,
    "createdAt": "2026-02-16T07:23:22.717Z",
    "images": [
      {
        "id": 67,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771226855050-123EC95D-9F48-4292-9576-7FF272705190_1_105_c-717c507f1a.jpg",
        "videoUrl": null,
        "altText": "96246012 2A71 42D9 85E2 77E5D3BAFAAE 1 105d scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      },
      {
        "id": 68,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771226871303-0012F1AD-66FD-41BD-91E0-34C5B5420FA5_1_105_c-7c0c6217a7.jpg",
        "videoUrl": null,
        "altText": "Scenic rendering study for project 96246012 2A71 42D9 85E2 77E5D3BAFAAE 1 105d, scenic design by Brandon PT Davis.",
        "caption": "",
        "title": "",
        "sortOrder": 1,
        "imageType": "rendering"
      },
      {
        "id": 69,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771226877260-2960BDC8-FC6F-4701-8E0C-5ADE2F536612_1_105_c-225ea8235b.jpg",
        "videoUrl": null,
        "altText": "Alternate scenic rendering angle for project 96246012 2A71 42D9 85E2 77E5D3BAFAAE 1 105d, scenic design by Brandon PT Davis.",
        "caption": "",
        "title": "",
        "sortOrder": 2,
        "imageType": "rendering"
      },
      {
        "id": 70,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771226885894-D729C095-12C8-469B-8DB5-EA601E086B3C_1_105_c-a45f759a5b.jpg",
        "videoUrl": null,
        "altText": "Concept rendering pass for project 96246012 2A71 42D9 85E2 77E5D3BAFAAE 1 105d, scenic design by Brandon PT Davis.",
        "caption": "",
        "title": "",
        "sortOrder": 3,
        "imageType": "rendering"
      }
    ]
  },
  {
    "id": 7,
    "category": "rendering",
    "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/experiential-process/rendering/1771227455469-83bbfb7c-e9f1-4f5c-97b4-bad4986df276_1_105_c.webp",
    "videoUrl": null,
    "altText": "",
    "displayTitle": "Wood Creek Distillery Activation",
    "description": "",
    "sortOrder": 5,
    "active": true,
    "projectId": 4,
    "year": null,
    "createdAt": "2026-02-16T07:37:37.508Z",
    "images": []
  },
  {
    "id": 13,
    "category": "rendering",
    "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/experiential-process/rendering/1771290715451-rab_render.webp",
    "videoUrl": null,
    "altText": "",
    "displayTitle": "Rab Activation",
    "description": "",
    "sortOrder": 6,
    "active": true,
    "projectId": 10,
    "year": 2025,
    "createdAt": "2026-02-17T01:11:57.597Z",
    "images": []
  },
  {
    "id": 14,
    "category": "rendering",
    "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/experiential-process/rendering/1771290861401-image1-enhanced.webp",
    "videoUrl": null,
    "altText": "",
    "displayTitle": "Toyota  Gold Cup Activation",
    "description": "",
    "sortOrder": 7,
    "active": true,
    "projectId": 11,
    "year": null,
    "createdAt": "2026-02-17T01:14:25.079Z",
    "images": [
      {
        "id": 111,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771290965345-Image1-39ac4253ed.jpg",
        "videoUrl": null,
        "altText": "Toyota  Gold Cup Activation scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      },
      {
        "id": 112,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771290968388-Image2-8f0a934b2b.jpg",
        "videoUrl": null,
        "altText": "Toyota  Gold Cup Activation scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      },
      {
        "id": 113,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771290970620-Image4-190ae6f96e.jpg",
        "videoUrl": null,
        "altText": "Toyota  Gold Cup Activation scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      },
      {
        "id": 114,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771290972787-Image5-4570ec4bc9.jpg",
        "videoUrl": null,
        "altText": "Toyota  Gold Cup Activation scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      },
      {
        "id": 115,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/project-images/migrated/external/1771290975327-Image8-6babe1f5ab.jpg",
        "videoUrl": null,
        "altText": "Toyota  Gold Cup Activation scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      }
    ]
  },
  {
    "id": 15,
    "category": "rendering",
    "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/experiential-process/rendering/1771293058270-rendering_park_and_shop_2.webp",
    "videoUrl": null,
    "altText": "",
    "displayTitle": "Park and Shop | Concord, CA",
    "description": "",
    "sortOrder": 8,
    "active": true,
    "projectId": 12,
    "year": null,
    "createdAt": "2026-02-17T01:51:00.682Z",
    "images": []
  },
  {
    "id": 19,
    "category": "rendering",
    "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/experiential-process/rendering/1771839325696-first_bank_lollipops.png",
    "videoUrl": null,
    "altText": "",
    "displayTitle": "First Bank Lollipops",
    "description": "",
    "sortOrder": 9,
    "active": true,
    "projectId": 16,
    "year": null,
    "createdAt": "2026-02-23T09:35:28.087Z",
    "images": []
  },
  {
    "id": 16,
    "category": "technical-drawing",
    "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/experiential-process/technical-drawing/1771838745874-design_drafting_park_and_shop_2.jpg",
    "videoUrl": null,
    "altText": "",
    "displayTitle": "Park & Shop Techncial Drawing",
    "description": "",
    "sortOrder": 1,
    "active": true,
    "projectId": 13,
    "year": null,
    "createdAt": "2026-02-23T09:25:48.534Z",
    "images": [
      {
        "id": 368,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/portfolio/general/2026/02/design-drafting-park-and-shop-1-2627.webp",
        "videoUrl": null,
        "altText": "Park & Shop Techncial Drawing scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      }
    ]
  },
  {
    "id": 17,
    "category": "technical-drawing",
    "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/experiential-process/technical-drawing/1771838895784-design_drafting_lysistrata_3.jpg",
    "videoUrl": null,
    "altText": "",
    "displayTitle": "Lysistrata Covid Documentation ",
    "description": "",
    "sortOrder": 2,
    "active": true,
    "projectId": 14,
    "year": null,
    "createdAt": "2026-02-23T09:28:17.949Z",
    "images": [
      {
        "id": 369,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/portfolio/general/2026/02/design-drafting-lysistrata-2-0658.webp",
        "videoUrl": null,
        "altText": "Lysistrata Covid Documentation  scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      },
      {
        "id": 370,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/portfolio/general/2026/02/design-drafting-lysistrata-4-2027.webp",
        "videoUrl": null,
        "altText": "Lysistrata Covid Documentation  scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      },
      {
        "id": 371,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/portfolio/general/2026/02/design-drafting-lysistrata-5-3362.webp",
        "videoUrl": null,
        "altText": "Lysistrata Covid Documentation  scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      },
      {
        "id": 372,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/portfolio/general/2026/02/design-drafting-lysistrata-6-4688.webp",
        "videoUrl": null,
        "altText": "Lysistrata Covid Documentation  scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      }
    ]
  },
  {
    "id": 18,
    "category": "technical-drawing",
    "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/experiential-process/technical-drawing/1771839189798-design_drafting_new_swan_3.jpg",
    "videoUrl": null,
    "altText": "",
    "displayTitle": "New Swan Venue Docuementation ",
    "description": "",
    "sortOrder": 3,
    "active": true,
    "projectId": 15,
    "year": null,
    "createdAt": "2026-02-23T09:33:12.784Z",
    "images": [
      {
        "id": 373,
        "imageUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/portfolio/general/2026/02/design-drafting-new-swan-4-2142.webp",
        "videoUrl": null,
        "altText": "New Swan Venue Docuementation  scenic design by Brandon PT Davis",
        "caption": "",
        "title": "",
        "sortOrder": 0,
        "imageType": "rendering"
      }
    ]
  }
];

export const generatedExperientialBrands = [
  {
    "id": 8,
    "name": "Rab",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771222466100-rab.png",
    "websiteUrl": "",
    "sortOrder": 2,
    "active": true
  },
  {
    "id": 9,
    "name": "cvs pharmacy",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771222659120-cvs-pharmacy.png",
    "websiteUrl": "",
    "sortOrder": 3,
    "active": true
  },
  {
    "id": 10,
    "name": "southwest airlines",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771222670695-southwest-airlines.png",
    "websiteUrl": "",
    "sortOrder": 4,
    "active": true
  },
  {
    "id": 11,
    "name": "caterpillar",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771222674382-pankaj-gupta-5.png",
    "websiteUrl": "",
    "sortOrder": 5,
    "active": true
  },
  {
    "id": 12,
    "name": "nvidia",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771222680019-nvidia.png",
    "websiteUrl": "",
    "sortOrder": 6,
    "active": true
  },
  {
    "id": 13,
    "name": "toyota",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771222701734-toyota.png",
    "websiteUrl": "",
    "sortOrder": 7,
    "active": true
  },
  {
    "id": 14,
    "name": "red bull",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771222705103-red-bull.png",
    "websiteUrl": "",
    "sortOrder": 8,
    "active": true
  },
  {
    "id": 15,
    "name": "herm s",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771223214202-herm-s.png",
    "websiteUrl": "",
    "sortOrder": 9,
    "active": true
  },
  {
    "id": 16,
    "name": "davines north america",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771223217835-davines-north-america.png",
    "websiteUrl": "",
    "sortOrder": 10,
    "active": true
  },
  {
    "id": 17,
    "name": "firstbank",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771223221396-firstbank.png",
    "websiteUrl": "",
    "sortOrder": 11,
    "active": true
  },
  {
    "id": 18,
    "name": "palo alto networks",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771223225068-palo-alto-networks.png",
    "websiteUrl": "",
    "sortOrder": 12,
    "active": true
  },
  {
    "id": 19,
    "name": "riken",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771223228628-riken.png",
    "websiteUrl": "",
    "sortOrder": 13,
    "active": true
  },
  {
    "id": 20,
    "name": "returnpro",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771223233519-returnpro.png",
    "websiteUrl": "",
    "sortOrder": 14,
    "active": true
  },
  {
    "id": 21,
    "name": "xrp ledger community",
    "logoUrl": "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/brands/1771223238893-xrp-ledger-community.png",
    "websiteUrl": "",
    "sortOrder": 15,
    "active": true
  }
];
