export const mediaBlobManifest: Record<string, string> = {
  "/assets/about/about-collaborators-art.png": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/about-collaborators-art-faba42fb.png",
  "/assets/about/about-process-art.png": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/about-process-art-b7051d34.png",
  "/assets/about/about-resume-art.png": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/about-resume-art-9d482ec3.png",
  "/assets/about/about-teaching-art.png": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/about-teaching-art-523a0d39.png",
  "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/gallery-behind-scenes.webp": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/gallery-behind-scenes-56903846.webp",
  "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/gallery-collaborations.webp": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/gallery-collaborations-3a11416a.webp",
  "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/gallery-family.webp": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/gallery-family-305c20d0.webp",
  "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/gallery-mentors.webp": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/gallery-mentors-de7b3237.webp",
  "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/gallery-partnerships.webp": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/gallery-partnerships-081c8f6b.webp",
  "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/gallery-teaching.webp": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/gallery-teaching-8566b656.webp",
  "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/gallery-teams.webp": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/gallery-teams-ee0e5092.webp",
  "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/gallery-uci.webp": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/gallery-uci-144f3c95.webp",
  "https://xibkuwouvisabnfowthn.supabase.co/storage/v1/object/public/about-images/profile-headshot.webp": "https://mpdddsg3xfx9bmy7.public.blob.vercel-storage.com/images/about/page/profile-headshot-a2c61b5a.webp",
};
