-- Ensure rendering_gallery exists
CREATE TABLE IF NOT EXISTS public.rendering_gallery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint REFERENCES public.projects(id) ON DELETE CASCADE,
    sort_order integer NOT NULL DEFAULT 0,
    alt_text text,
    display_title text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Add 'active' column to rendering_gallery if it doesn't exist
DO $$ BEGIN IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'rendering_gallery'
        AND column_name = 'active'
) THEN
ALTER TABLE public.rendering_gallery
ADD COLUMN active boolean DEFAULT true;
END IF;
END $$;
-- Enable RLS
ALTER TABLE public.rendering_gallery ENABLE ROW LEVEL SECURITY;
-- Ensure model_gallery exists
CREATE TABLE IF NOT EXISTS public.model_gallery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint REFERENCES public.projects(id) ON DELETE CASCADE,
    sort_order integer NOT NULL DEFAULT 0,
    alt_text text,
    display_title text,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Enable RLS
ALTER TABLE public.model_gallery ENABLE ROW LEVEL SECURITY;
-- Ensure experiential_gallery exists
CREATE TABLE IF NOT EXISTS public.experiential_gallery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint REFERENCES public.projects(id) ON DELETE CASCADE,
    sort_order integer NOT NULL DEFAULT 0,
    alt_text text,
    display_title text,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Enable RLS
ALTER TABLE public.experiential_gallery ENABLE ROW LEVEL SECURITY;
-- Grant permissions (safe to re-run)
GRANT ALL ON TABLE public.rendering_gallery TO postgres;
GRANT ALL ON TABLE public.rendering_gallery TO anon;
GRANT ALL ON TABLE public.rendering_gallery TO authenticated;
GRANT ALL ON TABLE public.rendering_gallery TO service_role;
GRANT ALL ON TABLE public.model_gallery TO postgres;
GRANT ALL ON TABLE public.model_gallery TO anon;
GRANT ALL ON TABLE public.model_gallery TO authenticated;
GRANT ALL ON TABLE public.model_gallery TO service_role;
GRANT ALL ON TABLE public.experiential_gallery TO postgres;
GRANT ALL ON TABLE public.experiential_gallery TO anon;
GRANT ALL ON TABLE public.experiential_gallery TO authenticated;
GRANT ALL ON TABLE public.experiential_gallery TO service_role;
-- Re-create policies to ensure they are correct (dropping if exists first)
DROP POLICY IF EXISTS "Allow public read access" ON public.rendering_gallery;
CREATE POLICY "Allow public read access" ON public.rendering_gallery FOR
SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.rendering_gallery;
CREATE POLICY "Allow authenticated insert" ON public.rendering_gallery FOR
INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Allow authenticated update" ON public.rendering_gallery;
CREATE POLICY "Allow authenticated update" ON public.rendering_gallery FOR
UPDATE TO authenticated USING (true);
DROP POLICY IF EXISTS "Allow authenticated delete" ON public.rendering_gallery;
CREATE POLICY "Allow authenticated delete" ON public.rendering_gallery FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS "Allow public read access on model_gallery" ON public.model_gallery;
CREATE POLICY "Allow public read access on model_gallery" ON public.model_gallery FOR
SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated insert on model_gallery" ON public.model_gallery;
CREATE POLICY "Allow authenticated insert on model_gallery" ON public.model_gallery FOR
INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Allow authenticated update on model_gallery" ON public.model_gallery;
CREATE POLICY "Allow authenticated update on model_gallery" ON public.model_gallery FOR
UPDATE TO authenticated USING (true);
DROP POLICY IF EXISTS "Allow authenticated delete on model_gallery" ON public.model_gallery;
CREATE POLICY "Allow authenticated delete on model_gallery" ON public.model_gallery FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS "Allow public read access on experiential_gallery" ON public.experiential_gallery;
CREATE POLICY "Allow public read access on experiential_gallery" ON public.experiential_gallery FOR
SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated insert on experiential_gallery" ON public.experiential_gallery;
CREATE POLICY "Allow authenticated insert on experiential_gallery" ON public.experiential_gallery FOR
INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Allow authenticated update on experiential_gallery" ON public.experiential_gallery;
CREATE POLICY "Allow authenticated update on experiential_gallery" ON public.experiential_gallery FOR
UPDATE TO authenticated USING (true);
DROP POLICY IF EXISTS "Allow authenticated delete on experiential_gallery" ON public.experiential_gallery;
CREATE POLICY "Allow authenticated delete on experiential_gallery" ON public.experiential_gallery FOR DELETE TO authenticated USING (true);