-- Create tutorials table if not exists
CREATE TABLE IF NOT EXISTS tutorials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  content TEXT,
  category TEXT,
  difficulty TEXT,
  duration INTEGER,
  video_url TEXT,
  cover_image TEXT,
  blocks JSONB DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add missing columns to tutorials
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft';
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT false;
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS seo_keywords TEXT;
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS learning_objectives JSONB DEFAULT '[]';
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS key_concepts JSONB DEFAULT '[]';
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS pro_tips JSONB DEFAULT '[]';
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS shortcuts JSONB DEFAULT '[]';
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS common_pitfalls JSONB DEFAULT '[]';
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS transcript JSONB DEFAULT '[]';
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS related_resources JSONB DEFAULT '[]';
ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS related_tutorials JSONB DEFAULT '[]';


-- Create collaborators table if not exists
CREATE TABLE IF NOT EXISTS collaborators (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  role TEXT,
  bio TEXT,
  website TEXT,
  portfolio_url TEXT,
  instagram_url TEXT,
  instagram_handle TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add missing columns to collaborators
ALTER TABLE collaborators ADD COLUMN IF NOT EXISTS cover_image TEXT;
ALTER TABLE collaborators ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'published';
ALTER TABLE collaborators ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT false;
ALTER TABLE collaborators ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE collaborators ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE collaborators ADD COLUMN IF NOT EXISTS seo_keywords TEXT;
ALTER TABLE collaborators ADD COLUMN IF NOT EXISTS gallery JSONB DEFAULT '[]';


-- Create scenic_directory table if not exists
CREATE TABLE IF NOT EXISTS scenic_directory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  category_name TEXT,
  category_slug TEXT,
  url TEXT,
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add missing columns to scenic_directory
ALTER TABLE scenic_directory ADD COLUMN IF NOT EXISTS cover_image TEXT;
ALTER TABLE scenic_directory ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'published';
ALTER TABLE scenic_directory ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT false;
ALTER TABLE scenic_directory ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE scenic_directory ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE scenic_directory ADD COLUMN IF NOT EXISTS seo_keywords TEXT;
ALTER TABLE scenic_directory ADD COLUMN IF NOT EXISTS gallery JSONB DEFAULT '[]';
