-- Create todos table if it doesn't exist
create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  text text not null,
  completed boolean default false,
  user_id uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.todos enable row level security;

-- Create policies
create policy "Users can view their own todos"
  on public.todos for select
  using (auth.uid() = user_id);

create policy "Users can create their own todos"
  on public.todos for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own todos"
  on public.todos for update
  using (auth.uid() = user_id);

create policy "Users can delete their own todos"
  on public.todos for delete
  using (auth.uid() = user_id);

-- Add todos to the realtime publication
alter publication supabase_realtime add table public.todos;
