-- Model Gallery
CREATE TABLE IF NOT EXISTS public.model_gallery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint REFERENCES public.projects(id) ON DELETE CASCADE,
    sort_order integer NOT NULL DEFAULT 0,
    alt_text text,
    display_title text,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Experiential Gallery
CREATE TABLE IF NOT EXISTS public.experiential_gallery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint REFERENCES public.projects(id) ON DELETE CASCADE,
    sort_order integer NOT NULL DEFAULT 0,
    alt_text text,
    display_title text,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- RLS Policies for Model Gallery
ALTER TABLE public.model_gallery ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on model_gallery" ON public.model_gallery FOR
SELECT TO public USING (true);
CREATE POLICY "Allow authenticated insert on model_gallery" ON public.model_gallery FOR
INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update on model_gallery" ON public.model_gallery FOR
UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete on model_gallery" ON public.model_gallery FOR DELETE TO authenticated USING (true);
-- RLS Policies for Experiential Gallery
ALTER TABLE public.experiential_gallery ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access on experiential_gallery" ON public.experiential_gallery FOR
SELECT TO public USING (true);
CREATE POLICY "Allow authenticated insert on experiential_gallery" ON public.experiential_gallery FOR
INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update on experiential_gallery" ON public.experiential_gallery FOR
UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete on experiential_gallery" ON public.experiential_gallery FOR DELETE TO authenticated USING (true);
-- Grant privileges
GRANT ALL ON TABLE public.model_gallery TO postgres;
GRANT ALL ON TABLE public.model_gallery TO anon;
GRANT ALL ON TABLE public.model_gallery TO authenticated;
GRANT ALL ON TABLE public.model_gallery TO service_role;
GRANT ALL ON TABLE public.experiential_gallery TO postgres;
GRANT ALL ON TABLE public.experiential_gallery TO anon;
GRANT ALL ON TABLE public.experiential_gallery TO authenticated;
GRANT ALL ON TABLE public.experiential_gallery TO service_role;