-- Enhanced analytics schema for session tracking, project views, and conversion funnels

-- Sessions table - tracks user journeys
CREATE TABLE IF NOT EXISTS public.analytics_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL UNIQUE,
  ip_address TEXT,
  city TEXT,
  region TEXT,
  country TEXT,
  user_agent TEXT,
  entry_page TEXT,
  exit_page TEXT,
  page_count INT DEFAULT 1,
  event_count INT DEFAULT 0,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  ended_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Project views table - tracks individual project interactions
CREATE TABLE IF NOT EXISTS public.analytics_project_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES public.analytics_sessions(session_id) ON DELETE CASCADE,
  project_id INT,
  project_slug TEXT,
  project_title TEXT,
  discipline TEXT,
  subcategory TEXT,
  time_on_page INT DEFAULT 0,
  scrolled BOOLEAN DEFAULT false,
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Generic events table - tracks actions (contacts, clicks, etc)
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES public.analytics_sessions(session_id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  event_data JSONB,
  page_path TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS analytics_sessions_city_idx ON public.analytics_sessions (city);
CREATE INDEX IF NOT EXISTS analytics_sessions_country_idx ON public.analytics_sessions (country);
CREATE INDEX IF NOT EXISTS analytics_sessions_started_at_idx ON public.analytics_sessions (started_at);
CREATE INDEX IF NOT EXISTS analytics_project_views_discipline_idx ON public.analytics_project_views (discipline);
CREATE INDEX IF NOT EXISTS analytics_project_views_project_slug_idx ON public.analytics_project_views (project_slug);
CREATE INDEX IF NOT EXISTS analytics_project_views_viewed_at_idx ON public.analytics_project_views (viewed_at);
CREATE INDEX IF NOT EXISTS analytics_events_type_idx ON public.analytics_events (event_type);
CREATE INDEX IF NOT EXISTS analytics_events_created_at_idx ON public.analytics_events (created_at);
