-- Create the rendering_gallery table
CREATE TABLE IF NOT EXISTS public.rendering_gallery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint REFERENCES public.projects(id) ON DELETE CASCADE,
    sort_order integer NOT NULL DEFAULT 0,
    alt_text text,
    -- Critical for SEO
    display_title text,
    -- Optional override
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Enable RLS
ALTER TABLE public.rendering_gallery ENABLE ROW LEVEL SECURITY;
-- Policies
CREATE POLICY "Allow public read access" ON public.rendering_gallery FOR
SELECT USING (true);
CREATE POLICY "Allow authenticated insert" ON public.rendering_gallery FOR
INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update" ON public.rendering_gallery FOR
UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete" ON public.rendering_gallery FOR DELETE TO authenticated USING (true);
-- Grant permissions
GRANT SELECT ON public.rendering_gallery TO anon,
    authenticated,
    service_role;
GRANT ALL ON public.rendering_gallery TO authenticated,
    service_role;